SET FOREIGN_KEY_CHECKS=0;
DROP TABLE IF EXISTS `test`;
DROP TABLE IF EXISTS `TODO`;
DROP TABLE IF EXISTS `CATEGORY`;
SET FOREIGN_KEY_CHECKS=1;

CREATE TABLE `test`(
	`id` INT AUTO_INCREMENT NOT NULL,
	`someInt` INT NOT NULL,
	PRIMARY KEY(`id`)
)ENGINE=InnoDB;

CREATE TABLE `TODO`(
	`id` INT AUTO_INCREMENT NOT NULL,
	`Name` VARCHAR(255) NOT NULL,
	`Urgency` VARCHAR(255) NOT NULL,
	`Date` DATETIME NOT NULL,
    `done` BOOLEAN DEFAULT 0,
    `Category` INT(11) DEFAULT 0,
	PRIMARY KEY(`id`)
)ENGINE=InnoDB;

CREATE TABLE `APPOINTMENT`(
	`id` INT AUTO_INCREMENT NOT NULL,
	`Name` VARCHAR(255) NOT NULL,
	`Location` VARCHAR(255) NOT NULL,
	`Date` DATETIME NOT NULL,
	`Description` VARCHAR(511) NOT NULL,
    `done` BOOLEAN DEFAULT 0,
	PRIMARY KEY(`id`)
)ENGINE=InnoDB;

CREATE TABLE `CATEGORY`(
	`id` INT AUTO_INCREMENT NOT NULL,
	`Name` VARCHAR(255) NOT NULL,
	PRIMARY KEY(`id`)
)ENGINE=InnoDB;
